version: "3"

services:

  identity-service:
    container_name: identity-service
    build:
      context: identity-verifier
    networks:
      - default
    ports:
    - "7000"

  proxy:
    container_name: proxy
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - identity-service
